### PR TITLE
proposed docker images

### PR DESCRIPTION
**Pull request by justin-napolitano**

### CODE REVIEW

**Comment by justin-napolitano** [comment]
The docker documentation is a little off.  I couldn't find the manifests when trying to pull  "latest" I propose two images.. one tagged cpu and another tagged -cuda.

something like docker pull sapienzanlp/relic-cpu:latest

**Comment by Riccorl** [comment]
Hi! Thank you for contributing to ReLiK!

You’re correct; there was an issue while pushing `sapienzanlp/relik:latest`, and it is not currently available. I’m not sure if we need separate repositories for the CUDA and CPU versions. Our original idea was to link the latest tag to the CUDA image.

**Comment by justin-napolitano** [comment]
Understood. My proposal was base on the structure of the docker hub repo.  I agree with you the latest should be the cuda as that is the most likely use case..(I think)

**Comment by justin-napolitano** [comment]
Feel free to close :)

**Pull request closed without merging**
